name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      
      # Ensure Nx CLI is installed
      - run: npm install -g nx

      # Reset Nx cache to avoid project graph processing issues
      - run: npx nx reset

      # Debugging: print environment variables
      - run: echo "NX_BASE=${{ env.NX_BASE }}"
      - run: echo "NX_HEAD=${{ env.NX_HEAD }}"

      # Debugging: Check Nx version
      - run: npx nx --version

      # Debugging: List directory contents and check configuration files
      - run: ls -la
      - run: cat nx.json
      - run: cat workspace.json || cat angular.json

      # Run Nx commands and capture detailed logs
      - name: Run Nx Format Check
        run: npx nx-cloud record -- nx format:check
        continue-on-error: true

      - name: Run Nx Affected Commands
        run: npx nx affected -t lint test build e2e-ci
        continue-on-error: true
